db:
  container_name: piwik-db
  image: mariadb
  restart: always
  volumes:
    - ./config/mariadb/base.cnf:/etc/mysql/conf.d/base.cnf:ro
    - ./data/mariadb:/var/lib/mysql

app:
  container_name: piwik-app
  build: .
  restart: always
  volumes:
    - ./data/piwik/config:/var/www/html/config

server:
  container_name: piwik-server
  image: nginx
  restart: always
  volumes:
    - ./config/nginx/base.conf:/etc/nginx/nginx.conf:ro

cron:
  container_name: piwik-cron
  build: .
  command: cron -f
  restart: always
  volumes:
    - ./config/piwik/crontab:/etc/cron.d/piwik
