db:
  extends:
    file: ../../docker-compose.yml
    service: db
  env_file:
    - ./.env

web:
  extends:
    file: ../../docker-compose.yml
    service: web
  links:
    - db
  env_file:
    - ./.env

server:
  extends:
    file: ../../docker-compose.yml
    service: server
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
  volumes_from:
    - web

cron:
  extends:
    file: ../../docker-compose.yml
    service: cron
  links:
    - db
  volumes_from:
    - web
